export const container1Element = document.querySelector(".container1") as HTMLElement
export const retryButtonLostElement = document.querySelector(".retry-button-lost")
export const retryButtonWinElement = document.querySelector(".retry-button-win")
export const controlsButtonElement = document.querySelector(".controls-button")
export const arrowBackElement = document.querySelector(".arrow-back")
export const startMenuElement = document.querySelector(".menu-start")
export const lostMenuElement = document.querySelector(".menu-lost")
export const winMenuElement = document.querySelector(".menu-win")
export const controlsMenuElement = document.querySelector(".menu-controls")
export const backMenuLostElement = document.querySelector(".back-menu-lost")
export const backMenuWinElement = document.querySelector(".back-menu-win")
export const githubElement = document.querySelector(".github")

export const easyButtonElement = document.querySelector(".easy")
export const mediumButtonElement = document.querySelector(".medium")
export const hardButtonElement = document.querySelector(".hard")
export const impossibleButtonElement = document.querySelector(".impossible")